<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Aleksandar" failures="3" tests="6" name="NegativeLoginTest-CH" time="19.579" errors="0" timestamp="2021-09-15T12:09:33 CEST">
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnLoginPage" time="1.091"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnLoginPage" time="0.662"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnLoginPage" time="1.105"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnMainPage" time="0.421">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&amp;amp;password=testPassword1]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnMainPage" time="0.416">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&amp;amp;password=incorrectPassword]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=testUsername1&password=incorrectPassword]
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfulLoginActionOnMainPage" time="0.514">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&amp;amp;password=incorrectPassword]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=incorrectPassword]
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfulLoginActionOnMainPage(NegativeLoginTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUnsuccessfulLoginActionOnMainPage -->
</testsuite> <!-- NegativeLoginTest-CH -->
