<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SIXNS289" failures="1" tests="2" name="NegativeLoginUsernameOnMainPageTest-FF" time="14.084" errors="0" timestamp="2021-09-13T15:37:47 CEST">
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfullLoginActionOnLoginPage" time="1.358"/>
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeLoginTests" name="verifyUnsuccessfullLoginActionOnMainPage" time="0.66">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&amp;amp;password=testPassword1]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/login] but found [http://localhost:8080/?username=incorrectUsername&password=testPassword1]
at local.HLVTestApp.loginandsignuptests.NegativeLoginTests.verifyUnsuccessfullLoginActionOnMainPage(NegativeLoginTests.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyUnsuccessfullLoginActionOnMainPage -->
</testsuite> <!-- NegativeLoginUsernameOnMainPageTest-FF -->
