<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SIXNS289" failures="1" tests="2" name="UserRegistrationTest4-FF" time="13.319" errors="0" timestamp="2021-09-10T12:55:27 CEST">
  <testcase classname="local.HLVTestApp.loginandsignuptests.PositiveSignUpTests" name="verifySuccessfullSignUpAction" time="1.523">
    <failure type="java.lang.AssertionError" message="expected [Oops! There is already a user registered with the email provided.] but found [User has been successfully registered.]">
      <![CDATA[java.lang.AssertionError: expected [Oops! There is already a user registered with the email provided.] but found [User has been successfully registered.]
at local.HLVTestApp.loginandsignuptests.PositiveSignUpTests.verifySuccessfullSignUpAction(PositiveSignUpTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifySuccessfullSignUpAction -->
  <testcase classname="local.HLVTestApp.loginandsignuptests.NegativeSignUpTests" name="verifyUnsuccessfullSignUpAction" time="0.0">
    <skipped/>
  </testcase> <!-- verifyUnsuccessfullSignUpAction -->
</testsuite> <!-- UserRegistrationTest4-FF -->
